### ISSUE TITLE
Add minify-on-save feature

### ISSUE THREAD

**Issue by ebewley** [Josee9988/MinifyAll#1]
**Is your feature request related to a problem? Please describe.**
Reduce keystrokes and eliminate issues in which project members forget to minify files upon saving.

**Describe the solution you'd like**
Add an option to the settings in vscode to minify on save.  Add another setting which instructs the extension to save to new files.  Add settings which allows the user to turn on/off the minimization of various types of files.  For example, if we want to minify all types except for HTML files, then let us select or deselect the option for HTML files.

**Describe alternatives you've considered**
Several minifiers include this functionality, and turn it off by default.  (Seems like it would reduce a greater number of issues and blamings in teams if it defaulted to on.)

**Comment by Josee9988** [comment]
Hi @ebewley  I'm going to try to make some things possible, sorry for not responding faster but I have been quite busy these days.
I find interesting turning on and off minimization of various types of files, going to start with that.

Minify on save seems like a good idea but I don't think this would be like a useful feature but definitely, I'll try to make it possible.

What do you mean by saving to new files? There is a secondary command that gets the actual code, minifies it and saves into a new file so you can still keep your readable code and have the minified version in the other file.

So much thanks for the ideas, definitely will work on that on the upcoming days, stay tuned!

**Comment by Josee9988** [comment]
@ebewley turning on and off minimization of each language has been added on version 0.8.2

And minify on save (your actual code or to a new file) has been added on version 0.8.3

Thanks for your time!

**Comment by ebewley** [comment]
Mr. Berenguer,

Thanks for responding, and for implementing those changes.  As soon as I
have sufficient time to reevaluate the extension, I'll let you know my
thoughts.

I had to switch back to the "JS and CSS Minify" extension because we
already began running into problems where people were forgetting to minify,
and code changes were not being picked up in TEST.  However, I'm looking
forward to re-implementing your product, since it minifies more than just
JS and CSS files.

Does your minify product support use of an external configuration file?  If
not, then allow me to explain why this is important to some of us (though
it should be important to everyone).  Continuity between all developers in
a team/project is vital, and in some cases, REQUIRED.  I am probably more
strict about coding standards and avoiding deviations than most, but it
comes from needing to require strict standards such as those for the
military, finance, and identity protection and fraud prevention
applications.  Everyone's code needs to meet the same standards, and that
includes minifying down to the same result on each and every machine.  To
achieve this, I require the use of read-only configuration files.  I allow
customization of themes, so its not good to restrict minor changes to
primary configuration files, but I do not allow customizations in how code
is validated for standards, or in the way that it is packaged for TEST,
INTEGRATION, and PRODUCTION environments.  I hope this helps.

Again, thank you for taking the time to read, understand, and implement the
changes I proposed.

Sincerely,
Eric Bewley

**Comment by Josee9988** [comment]
@ebewley 
Dear Mr Ebewley

MinifyAll does not support an external settings for the extension, but it does have some configuration settings for example of that lets you disable hexadecimal minimization.

I don't really think there is an standard for minifying files, it's simply making all the code into one line and removing some useless code and minifying for example hexadecimal or rgb values into 3 digit hexadecimals. But maybe there is one, I will try to find some information.

I do not really think I would add an external configuration file because I can let the user change the extension settings through VSCode and I think this is more simple and effective. 


I am always looking forward to improve my projects, and this one is not an exception, I truly understand what the problem that let you change to other minifier was, but I think is now solved. You can now go to the settings and enable minify on save (Every time you save the document it will save the minified text to other file or minify the actual code when you save) You can choose which one you prefeer.

I truly appreciate your comments and your intention to help me improve this extension.
Jose Gracia.
