### ISSUE TITLE
Add options to prevent minified files got minified again

### ISSUE THREAD

**Issue by RadhiFadlillah** [Josee9988/MinifyAll#10]
**Is your feature request related to a problem? Please describe.**

Sometimes when opening a `*.min.js` file, I might accidentally save the file. This is troubling because I'm using this extension with `minifyOnSave` set to `true`, which make the minified file get minified again. Sure, there is  fault in my part (I should stop reflexively press Ctrl+S after every seconds), however it might be better to add options to exclude some file from minifying process.

**Describe the solution you'd like**

Minified file shouldn't be minified again.

**Additional context**

If possible, could you also add settings to exclude some file or directories ? This feature will be useful to prevent VS Code settings and task configuration get minified by this extension.

**Comment by Josee9988** [comment]
This could be used only in the commands that create a new minified file.
I think this issue/enhancement is not a really big deal, and I don't really think this could help so much.
I understand what your problem is, but the solution might be more time spending for the user than just taking in mind to not save.

What I am trying to say is:

The extension might enable some absolute paths to not be used.
Or even and probably a good solution, some text to find in the filename to avoid it: suck as: '.min' and when you press save, it will match '.min' in the filename and will simply output a message.

I do not know if it is worth the time adding these measures or simply doing CTRL+Z in your code.

My main point is: It could be done but I do not see how this could benefit the extension at all. Doesn't seem to me like something to enhance.

Let me know what you think so we can try to find a better solution.

Thanks for your time @RadhiFadlillah !!

**Comment by RadhiFadlillah** [comment]
> I do not know if it is worth the time adding these measures or simply doing CTRL+Z in your code.

Yeah, I'm agree. I just realized the minified output is not automatically saved to file, which make it still undo-able.

With that said, I will close this issue. Thanks for the fast response :smile:
