### ISSUE TITLE
configuration only updates after restart

### ISSUE THREAD

**Issue by Cube707** [Josee9988/MinifyAll#132]
# **🚀 Feature Request: Live update all configurations**

## **Problem:**

Currently all configurations are loaded once on startup of the extentions. This means that after a configuration is changed, it will only take effect after a reload. This is slightly anoint when testing settings.

## **Describe the solution you'd like**

For Version 3.0 a callback handler should be implemented that updates the `IUserSettings` class when the usere chnages the configurations (if that is posible). Or at least the promt "reload window" should apperear.

**Comment by Josee9988** [comment]
You can try it if you want, that would be a pleasure :D
If not I could try to do it by the end of October.

Awaiting your response. :)

**Comment by Cube707** [comment]
I am not sure if the functionalaty should stay gloabal or if it should be put inside the `activate()` function?

**Comment by Josee9988** [comment]
Sorry for the delay, I don't know why but I didn't get a notification!

I've been testing out your code and it seems pretty good.

The functionality is good globally as you have made.

I would leave the second **if** statement only as `if (event.affectsConfiguration('MinifyAll')` so it triggers all MinifyAll changes.

Also, the handler is not useful in this case. It is making the configuration being loaded twice (when the user clicks reload and VSCode restarts, MinifyAll will load the configuration inside the handler and then it will load it again in the call `export var settings: IUserSettings = getUserSettings();`

So that variable should be left as a `const` as it was, and the callback could be safely removed!

---

Great job as always @Cube707 thanks for making these little improvements.

Modify these things and pull request it, or just pull request it and I'll modify it :D

**Comment by Cube707** [comment]
What I was trying to do is this:  
Whenever a "normal" option is changed, just call `settings = getUserSettings();` to update the settings in the internal variable. This will happen silently without the user noticing.  
The two options `minifyOnSave` and `minifyOnSaveToNewFile` are special, as they have a callback handler attacht to them, see here:

**Comment by Cube707** [comment]
I have it implementet and it should work now. I will do some more debugging and errorhunting tomorrow and open a pullrequest when I am sure I didn't do something to stupid.. XD
