### ISSUE TITLE
Been able to add custom file type (example: imljson is an JSON type)

### ISSUE THREAD

**Issue by AndyDaSilva52** [Josee9988/MinifyAll#23]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to use the tool with for example the file extension `.imljson`. This is a type of file from a Custom SDK. The syntax is the same as `.json`

**Describe the solution you'd like**
I think that one way to solve this is been able to configure this custom type related to another type of file, `.imljson` is the same as `.json`

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/1809812/77226235-8bcbc180-6b55-11ea-83bc-557e5009f6df.png)

![SNV_04453_2020-03-21_09-29-12](https://user-images.githubusercontent.com/1809812/77226361-80c56100-6b56-11ea-8e45-4b817f0bcd1f.gif)

![SNV_04451_2020-03-21_09-23-48](https://user-images.githubusercontent.com/1809812/77226264-c7668b80-6b55-11ea-9b11-abe869e408f0.gif)

**Comment by Josee9988** [comment]
Hi, @AndyDaSilva52 I understand your problem and fully understand what you want.
I'll try to take a look and see if I can add a custom rule.
Thanks for letting me know!

**Comment by AndyDaSilva52** [comment]
It will be great if anyone could add custom rules at the settings file. Tks

**Comment by Josee9988** [comment]
Hi again, @AndyDaSilva52 I'm afraid to say this will not be made at least for now.
I could successfully detect new file types by the user but this will break the entire structure of the application and since I don't have much time and this project is made only for me I will have to postpone it to the future.
For now, it will not be available.

I am so sorry for the inconvenience but as I told you the project is entirely made by me and I can't put all the effort I would like to as I don't have enough time. 

This project was one of my firsts and there are a lot of things that I don't like because it was made by a complete beginner and I choose to move on to other projects and kind of let this a part in a maintenance mode status. So tasks like this that need a lot of effort or time will simply be postponed or not made at all.

I am sorry :( You could just change the language mode and run the command otherwise it will not be possible.

**Comment by AndyDaSilva52** [comment]
I understand. Tks for all
