### ISSUE TITLE
Remove console.log from minified JS.

### ISSUE THREAD

**Issue by shyamkushwaha23** [Josee9988/MinifyAll#55]
**Is your feature request related to a problem? Please describe.**
In minified js, console.log statements not removed! I minified a js file and found this issue.

**Describe the solution you'd like**
From minified js, console.log statement should be removed.

**Describe alternatives you've considered**
We can add additional setting to remove console.log for js files, and default we can set it to true. So by default this extention will remove console.log statement from minified js. If use want they can disable it from the settings.

**Additional context**
N/A

**Comment by Josee9988** [comment]
I'll work on it as soon as I get in the pc.

Thanks for the issue

**Comment by Josee9988** [comment]
Hi @shyamkushwaha23 sorry for the late response but right now I'm on vacations and I don't spend nearly 1% of the time on the pc as I used to do.

Anyways, the issue is resolved. Make sure to download the latest MinifAll version (2.4.0) and test it out!

Thanks for contributing to this project :heart:

**Comment by shyamkushwaha23** [comment]
Hi @Josee9988. 

Now console.log statements getting removed.

Thanks :)
