### ISSUE TITLE
MinifyAll recently stopped working

### ISSUE THREAD

**Issue by lesfen** [Josee9988/MinifyAll#6]
There are several issues all of which prevent the extension from working at all.

CTRL ALT M produces error 'command'extension.MinifyAll' not found
Right Clicking the file in the explorer tree and click "Minify The selected document and preserve original" produces no error but does absolutely nothing.  

**To Reproduce**
right click on any css file in the file tree and click "Minify The selected document and preserve original"

Or open a css file and hit CTRL+ALT+M and see the error message

**Expected behavior**
It should have created a minified file.  

**Additional context**
I have tried uninstalling the extension and re-installing with no change.   I have no customized settings for the extension.  

I am running MinifyAll version 1.6.4

Here is my vscode version info
Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by Josee9988** [comment]
Hi, @lesfen I have tested the commands, and right-clicking in the explorer and Minify isn't working. Also using the keybinding CTRL + ALT +M isn't **detecting** a keybinding, but it works for me.

But this three commands in the picture are working perfectly for me. Calling them from the right-click menu or from the command palette.
![image](https://user-images.githubusercontent.com/38838976/68551099-a94f8880-0409-11ea-90c8-9b2eac9e535e.png)


I will anyway take a look to see why this explorer command has stopped working. And why the keybinding isn't detecting (probably because there are some more keybindings and chords with the same keys)

Thank you so much for your effort in trying to make this extension better, I'll try to do my best to fix these problems ASAP.

**Comment by lesfen** [comment]
I have solved the problem.  Something strange happened to my workspace file.  I discovered that the problem exists for ALL extensions and only when having this one workspace open.  It worked fine on other workspaces and for just opening folders.   Still no clue what happened, but deleting and recreating the workspace fixed it.

**Comment by Josee9988** [comment]
Hahahah, well at least you made me found an inconsistency thing in my code.
Thank you for your time @lesfen

**Comment by EnP-git** [comment]
hi I got same error now. do you know how can I fix this?

**Comment by Josee9988** [comment]
@EnP-git try disabling any other extension to see if this is caused by a 3rd party issue
