### ISSUE TITLE
Blade file type

### ISSUE THREAD

**Issue by wisnubaldas** [Josee9988/MinifyAll#7]
Does this not work in the file type ".blade.php"?

![image](https://user-images.githubusercontent.com/10908214/68821615-6586a880-06c1-11ea-9971-b87fe2470c90.png)

**Comment by Josee9988** [comment]
Hey, I'll check this in a couple of hours, stay tuned! 
Thanks for helping me improve the extension

**Comment by Josee9988** [comment]
Hey, @wisnubaldas I have been checking, and the extension works fine with '**.blade.php**' as well as '**.php**.
Remember that, the extension only allows PHP files (blade.php is still a PHP file) *in order to minify **HTML***.

We do not minify PHP, but we **can minify HTML in a PHP file**. 

The only command that is available for doing suck task is: ** 'Minify the selected text'. (CTRL+ALT+. CTRL+ALT+M).**

**You** may be using the **wrong command**.

I let you an example of me **minifying HTML** in a '*.blade.php*' file:

[Example](https://i.imgur.com/QJKZ7rD.mp4)

Thanks for helping anyway! Let me know what you think, and if I resolved your question :)
